spring.application.name=demo

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/phattrienungdung
# hoặc nếu có auth:
# spring.data.mongodb.uri=mongodb://username:password@localhost:27017/phattrienungdung

# Thay thế bằng MongoDB Atlas Connection String nếu dùng cloud:
# spring.data.mongodb.uri=mongodb+srv://username:password@cluster.mongodb.net/phattrienungdung
